export class Invoice {

    id?: number;
    docDt?: Date;
    docNo2?: string;
    vchId?: number;
    stockId?:any;
    partyId?: any;
    address?: string;
    totalQty?: number;
    docNo?: string;
    destBranch?: any;
    sourceStn?: string;
    consigneeDest?: any;
    consigneeadd?: string;
    consignerMobNo?: string;
    consigneename?: string;
    consigneeMobNo?: string;
    serAmt?: number;
    teriffLocation?: any;
    grossAmt?: number;
    netAmt2?: number;
    custName?: string;
    userId?: string;
    decVal?: number;
    decPer?: number;
    decamt?: number;
    status?: string;
    locationId?: string;
    noOfPieces?: number;
    creditAcc?: number;
    weight?: number;
    tariffId?: string;
    amount?: number;
    netAmt?: number;
    prefix?: string;
    cNoteNo?: string;
    partyLabel?: string;
    batchNo2?: string;
    productId?: number;
    qty?: number;
    qty2?: number;
    upload?: string;
    branchForwarding?: string;
    servTax?: number;
    fuelTax?: number;
    servAmt?: number;
    fuelAmt?: number;
    odCharges?: number;
    edcessPer?: number;
    shessPer?: number;
    shecessAmt?: number;
    educessAmt?: number;
    rptNetamt?: number;
    cntNo?: number;
    orginFld?: number;
    systemDate?: Date;
    consignerEmailId?: string;
    batchNo?: string;
    cardType?: string;
    dummy?: number;
    locationCode?: string;
    uploadTime?: Date;
    type?: string;
    invoiceNo?: string;
    cgst?: number;
    sgst?: number;
    cgstAmt?: number;
    sgstAmt?: number;
    cstCal?: number;
    gstCal?: number;
    igstCal?: number;
    igst?: number;
    igstAmt?: number;
    cgstDummy?: number;
    sgstDummy?: number;
    igstDummy?: number;
    source_st ? : number;
    time ? : number;
    cgst_dummy ? : number;
    sgst_dummy? : number;
    igst_dummy? : number;
    docketCharges?: number;
    refNo?: string;

}